masktools_filters_sources += [
  'mask/edge/edgemask.cpp',
  'mask/edge/edgemask16.cpp',
  'mask/edge/edgemask32.cpp',
  'mask/hysteresis/hysteresis.cpp',
  'mask/motion/motionmask.cpp',
  'mask/motion/motionmask16.cpp',
  'mask/motion/motionmask32.cpp'
]

masktools_filters_avx_sources += [
  'mask/edge/edgemask32_avx.cpp'
]

masktools_filters_avx2_sources += [
  'mask/edge/edgemask16_avx2.cpp',
  'mask/edge/edgemask_avx2.cpp'
]
