masktools_filters_sources += [
  'morphologic/deflate/deflate.cpp',
  'morphologic/deflate/deflate16.cpp',
  'morphologic/deflate/deflate32.cpp',
  'morphologic/expand/expand.cpp',
  'morphologic/expand/expand16.cpp',
  'morphologic/expand/expand32.cpp',
  'morphologic/inflate/inflate.cpp',
  'morphologic/inflate/inflate16.cpp',
  'morphologic/inflate/inflate32.cpp',
  'morphologic/inpand/inpand.cpp',
  'morphologic/inpand/inpand16.cpp',
  'morphologic/inpand/inpand32.cpp'
]
