masktools_filters_sources += [
  'support/adddiff/adddiff.cpp',
  'support/adddiff16/adddiff16.cpp',
  'support/average/average.cpp',
  'support/average16/average16.cpp',
  'support/clamp/clamp.cpp',
  'support/clamp16/clamp16.cpp',
  'support/makediff/makediff.cpp',
  'support/makediff16/makediff16.cpp'
]
